---
title: "Figure S2f - Reproducibility script"
author: "Wangjie Liu / Vincent Gardeux"
date: "2024/03/15"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./")
getwd()
```

## Libraries & functions

```{r}
suppressPackageStartupMessages(library(Seurat)) # For single-cell pipeline

cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
```

# read the Seurat object of functional TF atlas with all cycling cells

```{r}
data.seurat_integrated <- readRDS("results/C3H10_10X_all_exps_merged_genefiltered_integrated_filtered_functional_cycling.rds")
dim(data.seurat_integrated)
# 2000 24872
```

# Figure S2f

```{r Fig_S2f, fig.width=6.5, fig.height=5}
# color scheme for individual batch/experiment
cols <- c("#8DA0CB", "#E78AC3", "#A6D854","#FFD92F","#E5C494", "#66C2A5", "#FC8D62", "#FFCCCC")
names(cols) <- c("exp05", "exp06", "exp07", "exp08", "exp09", "exp10", "exp11", "exp12-13")

# plot functional TF atlas by batch

data.seurat_integrated$batch <- factor(data.seurat_integrated$batch, levels = c("exp12-13","exp05", "exp06", "exp07", "exp08", "exp09", "exp10", "exp11"))

p <- DimPlot(data.seurat_integrated, reduction = "umap", group.by = "batch", order = T) + 
    scale_color_manual(labels = c("1", "2", "3", "4", "5", "6", "7", "8"), values = cols) + 
        theme(axis.line = element_blank(),
        legend.position = "none", 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        axis.text=element_blank(), 
        axis.ticks=element_blank(), 
        plot.background=element_blank(), 
        panel.background=element_blank())+
  xlab(label = "") + ylab(label = "")+
  labs(title = NULL)
p

ggsave(p, filename = "figures/Fig_S2f.pdf", width = 6.5, height = 5)
```
