---
title: "Figure 1f - Reproducibility script"
author: "Wangjie Liu / Vincent Gardeux"
date: "2024/01/24"
output:
  html_document:
    df_print: paged
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/data/gardeux/TF-seq_proper/")
getwd()
```

## Libraries & functions

First, I'm loading the required libraries & functions

```{r}
suppressPackageStartupMessages(library(Seurat)) # For single-cell pipeline
suppressPackageStartupMessages(library(ggplot2)) # For plotting
suppressPackageStartupMessages(library(tidyverse)) # For %>%
suppressPackageStartupMessages(library(crayon)) # Just for bolding the console output :D

cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
cat(bold("ggplot2"), "version", as.character(packageVersion("ggplot2")), "\n")
cat(bold("tidyverse"), "version", as.character(packageVersion("tidyverse")), "\n")
```

# First, I'll read the final atlas Seurat object
```{r}
data.seurat <- readRDS("results/C3H10_10X_all_exps_merged_genefiltered_integrated_functional.rds")
dim(data.seurat) # 55536 39063
```
# Check TFs
```{r}
# All TFs
TFois <- unique(data.seurat$TF)

# Restrict to non-combination, non-control, non-ref
TFois <- TFois[!TFois %in% c("Mycn-Runx2", "Mycn-Myog", "Pparg-Runx2", "Cebpa-Pparg", "Cebpa-Myog", "Cebpa-Mycn", "Mycn-Pparg", "Adipo_ref", "Myo_ref", "D0", "D0_confluent")]

# Subset Seurat object
data.seurat <- subset(data.seurat, TF %in% TFois)

# Create summary
plotdata <- data.seurat@meta.data %>% 
  group_by(TF) %>% 
  mutate(TF_dose = Dose) %>% 
  group_by(TF) %>% 
  mutate(TF_dose_scaled = TF_dose  / max(TF_dose)) %>% 
  mutate(max_TF_dose = max(TF_dose)) 

plotdata$TF <- as.vector(plotdata$TF)
plotdata <- plotdata %>% group_by(TF) %>% arrange(desc(max_TF_dose)) 
plotdata$TF <- factor(plotdata$TF, levels = unique(plotdata$TF))
```

# Figure 1f

```{r Fig_1f, fig.width = 10, fig.height = 5}

# Subsample 
plotdata_sample <- plotdata %>%
  group_by(TF) %>%
  sample_n(min(n(), 500))

# Horizontal
p <- ggplot(plotdata_sample) +
  ggpointdensity::geom_pointdensity(mapping = aes(y = TF_dose, x = as.integer(TF))) +
  scale_color_viridis_c(guide = guide_colorbar(ticks = F, label = F, title.position="top", title.hjust = 0.5)) +
  labs(title = NULL, color = "Density", x = "TF", y = "TF dose (log(1 + TF-ID counts))") +
  scale_y_continuous(expand = c(0, 0)) +
  theme(legend.position = "top", legend.box = "horizontal", panel.grid.major = element_blank(), panel.grid.minor = element_blank(), panel.background = element_blank(), axis.ticks.x = element_blank(), axis.text.x = element_blank(), axis.line.y = element_line(), axis.title.x = element_text(size=12, color = "black"), axis.title.y = element_text(size=12, color = "black"), axis.text.y = element_text(size=14, color = "black"), plot.margin = unit(c(1,3,1,1), "lines")) +
  coord_cartesian(xlim = c(min(as.integer(plotdata_sample$TF)), max(as.integer(plotdata_sample$TF))), clip = 'off') # allow to draw outside plot area

# Now adding specific genes
genesoi <- c("Zfp369", "Zfp707", "Hes3", "Hoxa13", "Creb3", "Pparg", "Pou5f1", "Mycn", "Myog", "Runx2", "Cebpa", "Cdx4", "Nkx2-5", "Grhl3", "Prdm1", "Zc3h8", "Mbnl3", "Zfp663")
for(g in genesoi){
  xindex <- which(levels(plotdata_sample$TF) == g)
  p <- p + annotate("text", x = xindex, y = 0, label = toupper(g), angle = 90, size = 3, hjust = 1)
  p <- p + annotate("segment", x = xindex, xend = xindex, y = 0.5, yend = 0.1)
}

# Display and save plot
p
ggsave(p, filename = "figures/Fig_1f.pdf", width = 10, height = 5, dpi = 300)
```

