---
title: "Figure 1e - Reproducibility script"
author: "Wangjie Liu / Vincent Gardeux"
date: "2024/01/24"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/data/gardeux/TF-seq_proper/")
getwd()
```

## Libraries & functions

First, I'm loading the required libraries & functions

```{r}
suppressPackageStartupMessages(library(Seurat)) # For handling 10x h5 file
suppressPackageStartupMessages(library(ggplot2)) # For plotting
suppressPackageStartupMessages(library(crayon)) # Just for bolding the console output :D

cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
cat(bold("ggplot2"), "version", as.character(packageVersion("ggplot2")), "\n")

# color scheme
cols <- c("#8DA0CB", "#E78AC3", "#A6D854","#FFD92F","#E5C494", "#66C2A5", "#FC8D62", "#FFCCCC")
names(cols) <- c("exp05", "exp06", "exp07", "exp08", "exp09", "exp10", "exp11", "exp12-13")
```

# First, I'll read the final atlas Seurat object
```{r}
data.seurat <- readRDS("results/C3H10_10X_all_exps_merged_genefiltered_integrated_functional.rds")
dim(data.seurat) # 55536 39063
```

# Figure 1e


```{r Fig_1e, fig.width = 7, fig.height = 5}
arr <- list(x = -9.5, y = -6.5, x_len = 3, y_len = 3)

data.seurat$batch <- factor(data.seurat$batch, levels = c("exp05", "exp06", "exp07", "exp08", "exp09", "exp10", "exp11", "exp12-13"))

p <- DimPlot(data.seurat, reduction = "umap", group.by = "batch") + scale_color_manual(labels = c("1", "2", "3", "4", "5", "6", "7", "8"), values = cols) + annotate("segment", x = arr$x, xend = arr$x + c(arr$x_len, 0), y = arr$y, yend = arr$y + c(0, arr$y_len), arrow = arrow(type = "closed", length = unit(6, 'pt')))+ theme_void() + labs(title = NULL, color = "Batch")
p

ggsave(p, filename = "figures/Fig_1e.pdf", width = 7, height = 5)
```
