---
title: "Figure 2a, b - Reproducibility script"
author: "Wangjie Liu / Vincent Gardeux / Pernille"
date: "2024/01/25"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./")
getwd()
```

## Libraries & functions

First, I'm loading the required libraries & functions

```{r}
suppressPackageStartupMessages(library(Seurat)) # For single-cell pipeline
suppressPackageStartupMessages(library(ggplot2)) # For plotting
suppressPackageStartupMessages(library(tidyverse)) # For data tidying
suppressPackageStartupMessages(library(clustree)) # For clustering tree
suppressPackageStartupMessages(library(crayon)) # Just for bolding the console output :D

cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
cat(bold("ggplot2"), "version", as.character(packageVersion("ggplot2")), "\n")
cat(bold("tidyverse"), "version", as.character(packageVersion("tidyverse")), "\n")
cat(bold("clustree"), "version", as.character(packageVersion("clustree")), "\n")

# Random seed
set.seed(42)
```

# Read the functional TF atlas with functional TF cells, all S+G2M (default phase), D0 and ref cells

```{r}
data.seurat_integrated <- readRDS("results/C3H10_10X_all_exps_integrated_functional_TF_atlas_cycling_Phase.rds")
dim(data.seurat_integrated)
```

# Figure 2a

```{r}
# set color code
col <- readRDS("figures/Fig_2a_colorcode_TFs.rds")
# D0 = "black"
# D0_confluent = "gray52"
# most TFs = "gray85"
```


```{r Fig_2a, fig.width=6.5, fig.height=5}
# arr <- list(x = -9.5, y = -7.5, x_len = 3, y_len = 3)
p_umap <- DimPlot(data.seurat_integrated, group.by = "TF", cols = col) +
#       annotate("segment", x = arr$x, xend = arr$x + c(arr$x_len, 0), y = arr$y, yend = arr$y + c(0, arr$y_len), arrow = arrow(type = "closed", length = unit(6, 'pt')))+ 
  theme(axis.line = element_blank(),
        legend.position = "none", 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        axis.text=element_blank(), 
        axis.ticks=element_blank(), 
        plot.background=element_blank(), 
        panel.background=element_blank())+
  xlab(label = "") + ylab(label = "")+
  labs(title = NULL)
p_umap
ggsave(p_umap, filename = "figures/Fig_2a.pdf", width = 6.5, height = 5)
```

# plot same Figure 2a but with TFs of interest being labelled 

```{r}
TFoi <- c("D0","D0_confluent",
          "Adipo_ref","Myo_ref",
          "Mycn","Cebpa","Pparg","Myod1","Runx2","Myog",
          "Yap1","Tfeb",
          "Gata4","Gata3","Gata5","Gata2",
          "Klf4","Pdx1","Fos","Dlx6",
          "Nkx1-2","Hoxb6","Hoxa6","Hoxa9","Hoxa13","Cdx2","Cdx4",
          "Foxa1","Etv1","Ets1","Esr2","Sox2","Pou5f1",
          "Egr1","Hey1","Pax9","Grhl2","T","Pitx2","Mafb","Atf4",
          "Irf3","Lzts2","Hnf4a","Grhl2"
)

data.seurat_integrated$is.TFois <- data.seurat_integrated$TF %>% as.character()
data.seurat_integrated$is.TFois[!data.seurat_integrated$is.TFois %in% TFoi] <- NA
cols.oi <- col[TFoi]
cols.oi[NA] <- "gray85"
p_umap_label <- DimPlot(data.seurat_integrated, group.by = "is.TFois", cols = cols.oi, label = T, repel = T)+
      annotate("segment", x = arr$x, xend = arr$x + c(arr$x_len, 0), y = arr$y, yend = arr$y + c(0, arr$y_len), arrow = arrow(type = "closed", length = unit(6, 'pt')))+ 
  theme(axis.line = element_blank(),
        legend.position = "none", 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        axis.text=element_blank(), 
        axis.ticks=element_blank(), 
        plot.background=element_blank(), 
        panel.background=element_blank())+
  xlab(label = "") + ylab(label = "")+
  labs(title = NULL)
p_umap_label
```

# Figure 2b

```{r}
# find clusters for the functional TF atlas 
data.seurat_integrated <- data.seurat_integrated %>% FindNeighbors(dims = 1:100)
# run different resolution and then clustree to find an optimal resolution for clustering
for (i in seq(0.1, 1.5, 0.1)){
    data.seurat_integrated <- FindClusters(data.seurat_integrated, resolution = i, verbose = FALSE)
    p <- DimPlot(data.seurat_integrated, group.by = "seurat_clusters",label = T)+labs(title = paste0("resolution_",i))
    print(p)
}
clustree(data.seurat_integrated)
```

```{r Fig_2b, fig.width=6.5, fig.height=5}
# apply integrated_snn_res.0.2 for Figure 2b to present general cellular processes in the atlas
cols.cluster <- c("#99CCFF","#FFCCCC","#FFCC99","#FFFFCC","#FF9933","#99FF99","#CC00FF","#CCCC00","#FF99FF","#FF9999","#CC99CC")
names(cols.cluster) <- as.character(0:10)
cols.cluster


p <- DimPlot(data.seurat_integrated, group.by = "integrated_snn_res.0.2",label = T, order = T)+
    scale_color_manual(labels = c("0", "1", "2", "3", "4", "5","6","7"), values = cols.cluster)+
    theme(axis.line = element_blank(),
        legend.position = "none", 
        panel.grid.major=element_blank(), 
        panel.grid.minor=element_blank(), 
        axis.text=element_blank(), 
        axis.ticks=element_blank(), 
        plot.background=element_blank(), 
        panel.background=element_blank())+
  xlab(label = "") + ylab(label = "")+
  labs(title = NULL)
p
ggsave(p, filename = "figures/Fig_2b.pdf", width = 6.5, height = 5)
```
