---
title: "Figure 4a, b - reproducibility script"
author: "Wangjie Liu"
date: "2024-03-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "~/NAS2/TF-seq/Vincent/TF-seq_proper/")
getwd()
```

## Libraries & functions

First, I'm loading the required libraries & functions

```{r}
suppressPackageStartupMessages(library(Seurat, lib.loc = "~/.local/share/")) 
suppressPackageStartupMessages(library(data.table))
suppressPackageStartupMessages(library(ggplot2)) 
suppressPackageStartupMessages(library(cowplot)) 
suppressPackageStartupMessages(library(tidyverse))

cat(bold("R"), "version", as.character(version$version.string), "\n")
cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
cat(bold("data.table"), "version", as.character(packageVersion("data.table")), "\n")
cat(bold("ggplot2"), "version", as.character(packageVersion("ggplot2")), "\n")
cat(bold("cowplot"), "version", as.character(packageVersion("cowplot")), "\n")
cat(bold("tidyverse"), "version", as.character(packageVersion("tidyverse")), "\n")

# R version R version 4.3.1 (2023-06-16) 
# Seurat version 4.4.0 
# data.table version 1.15.2 
# ggplot2 version 3.5.0 
# cowplot version 1.1.3 
# tidyverse version 2.0.0 
```

## read the whole scTF-seq atlas and subset to G1 (Phase_corrected)

```{r}
seu <- readRDS("results/C3H10_10X_all_exps_merged_genefiltered_integrated_functional.rds")
seu <- subset(seu, Phase_corrected == "G1")
DefaultAssay(seu) <- "RNA"
dim(seu)
```

## read the annotation file

```{r}
data.annot <- fread("metadata/GRCm38_gene_annot.tsv", data.table = F) 
rownames(data.annot) <- data.annot$ensembl_id
```

## gene list for adiposcore

```{r}
Adipo <- c("Fabp4", "Lpl", "Pparg", "Lipe", "Adipoq", "Cd36",
          "Plin4", "Plin2", "Plin1", "Cebpa", "Cebpb",
          "Cidec", "Cidea")
Adipo <- data.annot[data.annot$gene_symbol %in% Adipo, "ensembl_id"]
```


```{r}
TFoi <- "Cebpa"
# use D0_conlfuent as strict control
seu.oi <- subset(seu, TF %in% c("D0_confluent","Cebpa"))

```

# Figure 4a

```{r Fig_4a}
# calculate adiposcore
seu.oi <- AddModuleScore(seu.oi, features = list(Adipo), name = "adiposcore_")
plotdata_adiposcore <- subset(seu.oi, TF %in% c("D0_confluent","Cebpa"))@meta.data[,c("adiposcore_1","Dose")]
colnames(plotdata_adiposcore) <- c("Adiposcore","Cebpa_dose")
p_adiposcore <- ggplot(plotdata_adiposcore, aes(x = Cebpa_dose, y = Adiposcore)) +
  geom_point(color = "#CCCC66", alpha = 0.8)+
  geom_smooth(show.legend = T, linewidth = 1.5,alpha = 0.15, color = "#999900")+ # se = F,
  theme_cowplot()
p_adiposcore
ggsave(p_adiposcore, filename =  "figures/Fig_4a.pdf", 
       height = 5, width = 6)

```

# Figure 4b

```{r Fig_4b}
cds <- GetAssayData(seu.oi, assay = "RNA", slot = "data")
gene.ois <- c("Pparg","Cebpd","Fabp5","C3")
plotdata_ois <- lapply(gene.ois, function(x){
  plotdata <- data.frame(dose = seu.oi$Dose, expression = cds[data.annot[data.annot$gene_symbol == x, "ensembl_id"], colnames(seu.oi)], gene = x)
})
plotdata_ois <- data.table::rbindlist(plotdata_ois)

p <- ggplot(plotdata_ois, aes(x = dose, y = expression, col = gene)) +
  scale_color_brewer(palette = "Dark2")+
  geom_smooth(show.legend = T, linewidth = 1.5,alpha = 0.15)+ # se = F,
  theme_cowplot()
p
ggsave(p, filename =  "figures/Fig_4b.pdf", 
       height = 5, width = 7)
```

