---
title: "Fiure 2c - Reproducibility script"
author: "Wangjie Liu"
date: "2024-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "./")
getwd()
```

## Libraries & functions

```{r}

suppressPackageStartupMessages(library(Seurat)) # For single-cell pipeline
suppressPackageStartupMessages(library(pheatmap)) # For hetamap plotting
suppressPackageStartupMessages(library(tidyverse)) # For data tidying


cat(bold("Seurat"), "version", as.character(packageVersion("Seurat")), "\n")
cat(bold("pheatmap"), "version", as.character(packageVersion("pheatmap")), "\n")
cat(bold("tidyverse"), "version", as.character(packageVersion("tidyverse")), "\n")
```

# Read the functional TF atlas with functional TF cells, D0 and ref cells in G1 at default phase

```{r}
data.seurat_integrated <- readRDS("results/C3H10_10X_all_exps_integrated_functional_TF_atlas_G1_Phase.rds")
dim(data.seurat_integrated)
```


# rename TFs

```{r}
data.seurat_integrated$TF[data.seurat_integrated$TF == "Nkx1-2"] <- "Nkx1_2"
data.seurat_integrated$TF[data.seurat_integrated$TF == "Nkx3-1"] <- "Nkx3_1"
data.seurat_integrated$TF[data.seurat_integrated$TF == "Nkx2-6"] <- "Nkx2_6"
```

# Figure 2c

```{r Fig_2c, fig.width=9, fig.height=7.5}
# extract cells for TFs or interest
TFoi <- c("Hoxa6","Hoxb6","Hoxa9","Hoxa13","Cdx2","Cdx4","Fos","Fosl1","Fosl2","Atf3","Atf4","Dlx3","Dlx6")
cells.oi <- colnames(data.seurat_integrated)[data.seurat_integrated$TF %in% TFoi]
length(cells.oi)

# check the involved batch
data.seurat_integrated$batch <- as.character(data.seurat_integrated$batch)
unique(data.seurat_integrated$batch[cells.oi]) # exp05 exp07 exp08 exp09 exp10 exp11

# set color scheme
my_colour = list(
  TF = c(Hoxa6 = '#a6cee3', Hoxb6 = '#1f78b4', Hoxa9 = "#6699CC", Hoxa13 = "#FF9933", 
         Cdx2 = '#FF9999', Cdx4 = '#FF0000', 
         Dlx3 = '#cab2d6',  Dlx6 = '#6a3d9a', 
         Fos = "#2b580c", Fosl1 = "#639a67", Fosl2 = "#d8ebb5",
         Atf3 = "#FFFF00", Atf4 = "#FFFFCC"),
  batch = c(
    exp05 = "#8da0cb", 
    exp07 = "#a6d854", 
    exp08 = "#ffd92f",
    exp09 = "#e5c494",
    exp10 = "#66c2a5", 
    exp11 = "#fc8d62"
  )
)

# calculate the pearson correlation of cells in the PCA space (100PCs)
cor_res_rep.sub <- Hmisc::rcorr(x = t(seu@reductions$pca@cell.embeddings[cells.oi,]), type = "pearson")
my_sample_col.sub <- seu@meta.data[cells.oi, "TF", drop = F] 
my_sample_row.sub <- seu@meta.data[cells.oi, "batch", drop = F]

# plot heatmap
p_heatmap <- pheatmap::pheatmap(cor_res_rep.sub$r, 
                        annotation_colors = my_colour,
                        annotation_row = my_sample_row.sub, annotation_col = my_sample_col.sub, 
                        show_colnames = F, show_rownames = F, clustering_method = "ward.D2")
p_heatmap
ggsave(p_heatmap, filename = "figures/Fig_2c.pdf", width = 9, height = 7.5)
```
